# NumPy Assignments 

#### 1. Import the numpy package under the name `np` (★☆☆)

In [2]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [3]:
import numpy as np
print(np.__version__)
np.show_config()

1.15.4
mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/anshumala/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/anshumala/anaconda3/include']
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/anshumala/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/anshumala/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/anshumala/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/anshumala/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/Users/anshumala/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/Users/anshumala/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs 

#### 3. Create a null vector of size 10 (★☆☆)

In [4]:
import numpy as np
Z = np.zeros(10)
print(Z)

Z = np.zeros([10,10])
print(Z)

Z = np.ones(10)
print(Z)

Z = np.ones((10,6))
print(Z)

[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


#### 4.  How to find the memory size of any array (★☆☆)

In [5]:
import numpy as np
Z = np.zeros((10,10))
print("%d bytes" % (Z.size * Z.itemsize))

800 bytes


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆)

In [6]:
%run `python -c "import numpy; numpy.info(numpy.add)"`

ERROR:root:File `'`python.py'` not found.


#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [7]:
import numpy as np
Z = np.zeros(10)
Z[4] = 1
print(Z)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆)
Note:

arange([start,] stop[, step,][, dtype]) : Returns an array with evenly spaced elements as per the interval. The interval mentioned is half opened i.e. [Start, Stop)

start : [optional] start of interval range. By default start = 0

stop : end of interval range
step : [optional] step size of interval. By default step size = 1,
For any output out, this is the distance between two adjacent values, out[i+1] - out[i].
dtype : type of output array

In [8]:
import numpy as np
Z = np.arange(10,50)
print(Z)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8.  Reverse a vector (first element becomes last) (★☆☆)

In [9]:
import numpy as np
Z = np.arange(50)
Z = Z[::-1]
print(Z)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10  9  8  7  6  5  4  3  2
  1  0]


#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [10]:
import numpy as np
Z = np.arange(9).reshape(3,3)
print(Z)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆)
Note:

* numpy.nonzero()function is used to Compute the indices of the elements that are non-zero.
It returns a tuple of arrays, one for each dimension of arr, containing the indices of the non-zero elements in that dimension.

In [11]:
import numpy as np
nz = np.nonzero([1,2,0,0,4,0])
print(nz)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)
Note : eye() Return a 2-D array with ones on the diagonal and zeros elsewhere.

In [12]:
import numpy as np
Z = np.eye(3)
print(Z)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)
Note:
* numpy.random.random(size=None) Return random floats in the half-open interval [0.0, 1.0).

* Results are from the “continuous uniform” distribution over the stated interval.

In [13]:
import numpy as np
Z = np.random.random((3,3,3))
print(Z)

[[[5.03366591e-01 6.17780237e-01 3.44074895e-02]
  [6.98317914e-01 8.32518092e-01 1.20845923e-01]
  [9.48013505e-01 4.94295333e-01 3.79884924e-01]]

 [[6.35702609e-04 3.63082094e-02 8.59532269e-01]
  [7.65399427e-02 4.90977966e-01 2.22620457e-01]
  [9.54927290e-01 9.19512233e-01 1.30639170e-01]]

 [[8.45637173e-01 7.77108332e-01 9.42087665e-01]
  [5.00784596e-02 5.04865490e-01 9.01843546e-01]
  [4.51229705e-01 6.90066662e-01 3.48114617e-01]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [14]:
import numpy as np
Z = np.random.random((10,10))
Zmin, Zmax = Z.min(), Z.max()# random values will be in between of o to 1 vlues
print(Zmin, Zmax)

0.005061670940677443 0.9876427954636648


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [15]:
import numpy as np
pp = np.random.random(30)
m = pp.mean()
print(m)

0.4192141698224098


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [16]:
import numpy as np
Z = np.ones((10,10))
Z[1:-1,1:-1] = 0
print(Z)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [17]:
import numpy as np
Z = np.ones((5,5))
Z = np.pad(Z, pad_width=1, mode='constant', constant_values=0)
print(Z)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
Note:

* NaNs can be used as a poor-man’s mask (if you don’t care what the original value was)
* cannot use equality to test NaNs

In [18]:
import numpy as np
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(np.nan in set([np.nan]))
print(0.3 == 3 * 0.1)

nan
False
False
nan
True
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)
Note: 
* Extract a diagonal or construct a diagonal array.

In [2]:
import numpy as np
Z = np.diag(1+np.arange(4),k=-1)
print(Z)

y = np.diag(2+np.arange(4),k=-1)
print('\n',y)

a = np.diag(1+np.arange(4),k=1)
print('\n',a)



[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]

 [[0 0 0 0 0]
 [2 0 0 0 0]
 [0 3 0 0 0]
 [0 0 4 0 0]
 [0 0 0 5 0]]

 [[0 1 0 0 0]
 [0 0 2 0 0]
 [0 0 0 3 0]
 [0 0 0 0 4]
 [0 0 0 0 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)
Note:

* In your given example, z[::2] and z[1::2]. So, you are simply exchanging the values. But what are the values.

* z[::2] means range selection between 0 and len(L) with step 2. That is, select 0th, 2nd, 4th, …, and so on.

* z[1::2] means range selection between 1 and len(L) with step 2. That is, select 1st, 3rd, 5th, …, and so on.

In [20]:
import numpy as np
Z = np.zeros((8,8),dtype=int)
Z[1::2,::2] = 1# blank is equal to zera value.
Z[::2,1::2] = 1
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element.
Note:

* Converts a flat index or array of flat indices into a tuple of coordinate arrays.
* Parameters:
    indices : array_like An integer array whose elements are indices into the flattened version of an array of dimensions dims.

    dims : tuple of ints The shape of the array to use for unraveling indices.

    order : {‘C’, ‘F’}, optional Determines whether the indices should be viewed as indexing in row-major (C-style) or column-major (Fortran-style) order.

In [4]:
import numpy as np
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)
Note:

* Construct an array by repeating A the number of times given by reps.
* Parameters:
    A : array_like The input array.

    reps : array_like The number of repetitions of A along each axis.

In [3]:
import numpy as np
Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [6]:
import numpy as np
Z = np.random.random((5,5))
Z = (Z - np.mean (Z)) / (np.std (Z))
print(Z)



[[-0.09105997  0.91734704 -1.45523998 -0.28658732 -0.02633551]
 [ 1.02775887  1.62516562  1.09475943  0.2618414   1.1707368 ]
 [-0.47954405  0.3327775  -0.38159949 -1.39031932 -0.26606562]
 [ 1.9370665  -1.01894614 -1.40993074 -0.37799367  0.38380011]
 [-0.88108351 -1.08475884 -1.21401436  1.62139093 -0.00916566]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [24]:
import numpy as np
color = np.dtype([("r", np.ubyte, 1),
                  ("g", np.ubyte, 1),
                  ("b", np.ubyte, 1),
                  ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [22]:
import numpy as np
Z = np.dot(np.ones((5,3)), np.ones((3,2)))
print(Z)

# Alternative solution, in Python 3.5 and above
Z = np.ones((5,3)) @ np.ones((3,2))

[[3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]
 [3. 3.]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [21]:


import numpy as np
Z = np.arange(11)
Z[(3 < Z) & (Z <= 8)] *= -1 #values greater than 2 and less than 8 becomes negative value
print(Z)

[ 0  1  2  3 -4 -5 -6 -7 -8  9 10]


#### 26. What is the output of the following script? (★☆☆)

In [4]:

import numpy as np

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

In [10]:
#import numpy as np
Z=[1,2,3,4]
#print(Z**Z)
#print(2 << Z >> 2)
#print(Z <- Z)(bad operand type for unary -: 'list')
#print(1j*Z)(can't multiply sequence by non-int of type 'complex')
#print(Z/1/1)(unsupported operand type(s) for /: 'list' and 'int')
print(Z<Z>Z)

False


#### 28. What are the result of the following expressions?

In [19]:
import numpy as np
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/Users/anshumala/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in true_divide
  
/Users/anshumala/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:3: RuntimeWarning: divide by zero encountered in floor_divide
  This is separate from the ipykernel package so we can avoid doing imports until


#### 29. How to round away from zero a float array ? (★☆☆)
Note:

* uniform: Draw samples from a uniform distribution.
Samples are uniformly distributed over the half-open interval [low, high) (includes low, but excludes high). In other words, any value within the given interval is equally likely to be drawn by uniform.
* copysign(x,y): Return x with the sign of y. On a platform that supports signed zeros, copysign(1.0, -0.0) returns -1.0.
* ceil(x): Return the ceiling of x as a float, the smallest integer value greater than or equal to x.
* abs(x): Return the absolute value of x.


In [67]:


import numpy as np
Z = np.random.uniform(-10,+10,10)
#print(Z)
#y=np.abs(Z)
#print(y)
#x=np.ceil(y)
#print(x)

print (np.copysign(np.ceil(np.abs(Z)), Z))

[ -9.  -1.  -6.  -9. -10.  -4.  -2.   8.  -3.   6.]


#### 30. How to find common values between two arrays? (★☆☆)

Note:

* Randint (a, b): Return a random integer N such that a <= N <= b .
* intersect1d: Return the sorted, unique values that are in both of the input arrays.

In [17]:
import numpy as np
Z1 = np.random.randint(0,10,10)
Z2 = np.random.randint(0,10,10)
print(np.intersect1d(Z1,Z2))

[1 3 4 5 6 7 8]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆)
* seterr():Set how floating-point errors are handled.

* Note that operations on integer scalar types (such as int16) are handled like floating point, and are affected by these settings.
* errstate(): Context manager for floating-point error handling.
    Using an instance of errstate as a context manager allows statements in that context to execute with a known error handling behavior. Upon entering the context the error handling is set with seterr and seterrcall, and upon exiting it is reset to what it was before.

In [16]:
# Suicide mode on
import numpy as np
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
print(Z)

# Back to sanity
_ = np.seterr(**defaults)

#An equivalent way, with a context manager:

with np.errstate(divide='ignore'):
    Z = np.ones(1) / 0
    print(Z)

[inf]
[inf]


#### 32. Is the following expressions true? (★☆☆)
Note:
* np.sqrt():Return the non-negative square-root of an array, element-wise.

In [11]:
import numpy as np
np.sqrt(-1) == np.emath.sqrt(-1)

/Users/anshumala/anaconda3/lib/python3.7/site-packages/ipykernel_launcher.py:2: RuntimeWarning: invalid value encountered in sqrt
  


False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆)

In [26]:
import numpy as np
yesterday = np.datetime64('today', 'D') - np.timedelta64(1, 'D')
today     = np.datetime64('today', 'D')
tomorrow  = np.datetime64('today', 'D') + np.timedelta64(1, 'D')
yesterday
today
tomorrow

numpy.datetime64('2019-02-09')

#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆)

In [27]:
import numpy as np
Z = np.arange('2016-07', '2016-08', dtype='datetime64[D]')
print(Z)

['2016-07-01' '2016-07-02' '2016-07-03' '2016-07-04' '2016-07-05'
 '2016-07-06' '2016-07-07' '2016-07-08' '2016-07-09' '2016-07-10'
 '2016-07-11' '2016-07-12' '2016-07-13' '2016-07-14' '2016-07-15'
 '2016-07-16' '2016-07-17' '2016-07-18' '2016-07-19' '2016-07-20'
 '2016-07-21' '2016-07-22' '2016-07-23' '2016-07-24' '2016-07-25'
 '2016-07-26' '2016-07-27' '2016-07-28' '2016-07-29' '2016-07-30'
 '2016-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆)

In [38]:
import numpy as np
A = np.ones(3)*1
print(A)
B = np.ones(3)*2
print(B)
C = np.ones(3)*3
print(C)
print('\n add:',np.add(A,B,out=B))
print('\n divide:',np.divide(A,2,out=A))
print('\n negative:',np.negative(A,out=A))
print('\n multiply:',np.multiply(A,B,out=A))

[1. 1. 1.]
[2. 2. 2.]
[3. 3. 3.]

 add: [3. 3. 3.]

 divide: [0.5 0.5 0.5]

 negative: [-0.5 -0.5 -0.5]

 multiply: [-1.5 -1.5 -1.5]


In [40]:
import numpy as np
A = np.ones(3)*1
A

array([1., 1., 1.])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆)
Note:
* numpy.trunc(x[, out]) = ufunc ‘trunc’) : This mathematical function returns the truncated value of the elements of array. The trunc of the scalar x is the nearest integer i which, closer to zero than x. This simply means that, the fractional part of the signed number x is discarded by this function.
* astype(): Copy of the array, cast to a specified type.


In [42]:
import numpy as np
Z = np.random.uniform(0,10,10)

print (Z - Z%1)
print ('\n floor value:',np.floor(Z))
print ('\n ceil value:',np.ceil(Z)-1)
print ('\n astypr value:',Z.astype(int))
print ('\n trunc value:',np.trunc(Z))

[2. 5. 1. 0. 5. 9. 0. 6. 7. 4.]

 floor value: [2. 5. 1. 0. 5. 9. 0. 6. 7. 4.]

 ceil value: [2. 5. 1. 0. 5. 9. 0. 6. 7. 4.]

 astypr value: [2 5 1 0 5 9 0 6 7 4]

 trunc value: [2. 5. 1. 0. 5. 9. 0. 6. 7. 4.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆)

In [43]:
import numpy as np
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆)
Note:
* fromiter():Create a new 1-dimensional array from an iterable object.
* yield: The yield statement suspends function’s execution and sends a value back to caller, but retains enough state to enable function to resume where it is left off. When resumed, the function continues execution immediately after the last yield run. This allows its code to produce a series of values over time, rather them computing them at once and sending them back like a list.

In [44]:
import numpy as np
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆)
    * Return evenly spaced numbers over a specified interval.
    Returns num evenly spaced samples, calculated over the interval [start, stop].
    The endpoint of the interval can optionally be excluded.

In [49]:
import numpy as np
Z = np.linspace(0,1,11,endpoint=False)[1:]
print(Z)

Z = np.linspace(0,11,11,endpoint=False)[1:]
print(Z)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


#### 40. Create a random vector of size 10 and sort it (★★☆)
Note:
* By default, sort() doesn't require any extra parameters. However, it has two optional parameters:
    - reverse - If true, the sorted list is reversed (or sorted in Descending order)
    - key - function that serves as a key for the sort comparison

In [50]:
import numpy as np
Z = np.random.random(10)
Z.sort()
print(Z)

[0.01343707 0.08849652 0.3167245  0.38170091 0.44574357 0.61558042
 0.87909341 0.88173608 0.91401338 0.95627172]


#### 41. How to sum a small array faster than np.sum? (★★☆)
Note:
* numpy.ufunc.reduce. Reduces a's dimension by one, by applying ufunc along one axis. For example, add.reduce() is equivalent to sum(). Axis or axes along which a reduction is performed.

In [51]:

import numpy as np
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆)
Note: 
* Randint (a, b): Return a random integer N such that a <= N <= b .
* allclose() : Returns True if two arrays are element-wise equal within a tolerance.

    - The tolerance values are positive, typically very small numbers. The relative difference (rtol * abs(b)) and the absolute difference atol are added together to compare against the absolute difference between a and b.

    - If either array contains one or more NaNs, False is returned. Infs are treated as equal if they are in the same place and of the same sign in both arrays.
* array_equal(): True if two arrays have the same shape and elements, False otherwise.

In [52]:
import numpy as np
A = np.random.randint(0,2,5)
B = np.random.randint(0,2,5)

# Assuming identical shape of the arrays and a tolerance for the comparison of values
equal = np.allclose(A,B)
print(equal)

# Checking both the shape and the element values, no tolerance (values have to be exactly equal)
equal = np.array_equal(A,B)
print(equal)

False
False


#### 43. Make an array immutable (read-only) (★★☆)
Note:
* flags : Information about the memory layout of the array.
* The array flags cannot be set arbitrarily:

    - UPDATEIFCOPY can only be set False.
    - WRITEBACKIFCOPY can only be set False.
    - ALIGNED can only be set True if the data is truly aligned.
    - WRITEABLE can only be set True if the array owns its own memory or the ultimate owner of the memory exposes a writeable buffer interface or is a string.

In [57]:
import numpy as np
Z = np.zeros(10)
Z.flags.writeable = False
Z[0] =1


ValueError: assignment destination is read-only

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆)
Note: 
* Element-wise arc tangent of x1/x2 choosing the quadrant correctly.

    The quadrant (i.e., branch) is chosen so that arctan2(x1, x2) is the signed angle in radians between the ray ending at the origin and passing through the point (1,0), and the ray ending at the origin and passing through the point (x2, x1). (Note the role reversal: the “y-coordinate” is the first function parameter, the “x-coordinate” is the second.) By IEEE convention, this function is defined for x2 = +/-0 and for either or both of x1 and x2 = +/-inf (see Notes for specific values).

    This function is not defined for complex-valued arguments; for the so-called argument of complex values, use 

In [58]:
import numpy as np
Z = np.random.random((10,2))
X,Y = Z[:,0], Z[:,1]
R = np.sqrt(X**2+Y**2)
T = np.arctan2(Y,X)
print(R)
print(T)

[0.90754077 1.00759022 1.01123831 0.96979533 0.72350217 1.10721892
 0.3626563  1.34852998 1.01343355 1.08356153]
[0.46585921 1.03146087 1.34102777 0.4893694  0.16401258 1.0798938
 0.76944315 0.78200775 1.10844418 0.73494601]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆)
Note: 
* numpy.argmax(array, axis = None, out = None) : Returns indices of the max element of the array in a particular axis.

In [59]:
import numpy as np
Z = np.random.random(10)
Z[Z.argmax()] = 0
print(Z)

[0.51521474 0.67157857 0.18161557 0.88388419 0.2653197  0.
 0.93305119 0.43778717 0.17445691 0.29315838]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆)
Note:
* np.meshgrid(): Return coordinate matrices from coordinate vectors.
    - Make N-D coordinate arrays for vectorized evaluations of N-D scalar/vector fields over N-D grids, given one-dimensional coordinate arrays x1, x2,…, xn.

In [60]:
import numpy as np
Z = np.zeros((5,5), [('x',float),('y',float)])
Z['x'], Z['y'] = np.meshgrid(np.linspace(0,1,5),
                             np.linspace(0,1,5))
print(Z)

[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj))
Note:
* np.subtract.outer() : Apply the ufunc op to all pairs (a, b) with a in A and b in B.
Let M = A.ndim, N = B.ndim. Then the result, C, of op.outer(A, B) is an array of dimension M + N /M * N/M-N
* np.linalg.det() : Compute the determinant of an array.


In [67]:

import numpy as np
X = np.arange(8)
print(X)
Y = X + 0.5
print(Y)
C = 1.0 / np.subtract.outer(X, Y)
print('\n',C)
print('\n',np.linalg.det(C))

[0 1 2 3 4 5 6 7]
[0.5 1.5 2.5 3.5 4.5 5.5 6.5 7.5]

 [[-2.         -0.66666667 -0.4        -0.28571429 -0.22222222 -0.18181818
  -0.15384615 -0.13333333]
 [ 2.         -2.         -0.66666667 -0.4        -0.28571429 -0.22222222
  -0.18181818 -0.15384615]
 [ 0.66666667  2.         -2.         -0.66666667 -0.4        -0.28571429
  -0.22222222 -0.18181818]
 [ 0.4         0.66666667  2.         -2.         -0.66666667 -0.4
  -0.28571429 -0.22222222]
 [ 0.28571429  0.4         0.66666667  2.         -2.         -0.66666667
  -0.4        -0.28571429]
 [ 0.22222222  0.28571429  0.4         0.66666667  2.         -2.
  -0.66666667 -0.4       ]
 [ 0.18181818  0.22222222  0.28571429  0.4         0.66666667  2.
  -2.         -0.66666667]
 [ 0.15384615  0.18181818  0.22222222  0.28571429  0.4         0.66666667
   2.         -2.        ]]

 3638.1636371179666


#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆)
Note:
* np.iinfo(): Machine limits for integer types.
* np.finfo() : Machine limits for floating point types.
    - epsilon(eps) is the smallest positive floating point number such that (1 + epsilon) - 1 equals epsilon.

In [69]:
import numpy as np
for dtype in [np.int8, np.int32, np.int64]:
   print('minimum :',np.iinfo(dtype).min)
   print('maximum :',np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print('minimum :',np.finfo(dtype).min)
   print('maximum :',np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

minimum : -128
maximum : 127
minimum : -2147483648
maximum : 2147483647
minimum : -9223372036854775808
maximum : 9223372036854775807
minimum : -3.4028235e+38
maximum : 3.4028235e+38
1.1920929e-07
minimum : -1.7976931348623157e+308
maximum : 1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆)
Note:
* Set printing options.
These options determine the way floating point numbers, arrays and other NumPy objects are displayed.
    - threshold : int, optional
        Total number of array elements which trigger summarization rather than full repr (default 1000).

In [70]:
import numpy as np
np.set_printoptions(threshold=np.nan)
Z = np.zeros((16,16))
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆)
Note:
* argmin(): Returns the indices of the minimum values along an axis.

In [77]:
import numpy as np
Z = np.arange(100)
print(Z)
v = np.random.uniform(0,100)
print('\n',v)
index = (np.abs(Z-v)).argmin()
print('\n',index)
print(Z[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]

 47.750191260791105

 48
48


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆)

In [78]:
import numpy as np
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆)
Note:
* np.atleast_2d() : View inputs as arrays with at least two dimensions.
* scipy : The scipy namespace itself only contains functions imported from numpy. These functions still exist for backwards compatibility, but should be imported from numpy directly.
 - Everything in the namespaces of scipy submodules is public. In general, it is recommended to import functions from submodule namespaces. 

In [ ]:
import numpy as np
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

# Much faster with scipy
import scipy
# Thanks Gavin Heverly-Coulson (#issue 1)
import scipy.spatial

Z = np.random.random((10,2))
D = scipy.spatial.distance.cdist(Z,Z)
print(D)

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place?
Note:
* astype(): Copy of the array, cast to a specified type.

In [9]:
import numpy as np
Z = np.arange(10, dtype=np.float32)
print(Z)
Z = Z.astype(np.int32)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]
[0 1 2 3 4 5 6 7 8 9]


#### 54. How to read the following file? (★★☆)
Note :
* Class StringIO.StringIO
  -  When a StringIO object is created, it can be initialized to an existing string by passing the string to the constructor. If no string is given, the StringIO will start empty. In both cases, the initial file position starts at zero.

  -  The StringIO object can accept either Unicode or 8-bit strings, but mixing the two may take some care. If both are used, 8-bit strings that cannot be interpreted as 7-bit ASCII (that use the 8th bit) will cause a UnicodeError to be raised when getvalue() is called.
* genfromtxt() : Load data from a text file, with missing values handled as specified.

Each line past the first skip_header lines is split at the delimiter character, and characters following the comments character are discarded.

In [1]:
import numpy as np
from io import StringIO

# Fake file 
s = StringIO("""1, 2, 3, 4, 5\n
                6,  ,  , 7, 8\n
                 ,  , 9,10,11\n""")
Z = np.genfromtxt(s, delimiter=",", dtype=np.int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆)
Note:
* ndenumerate() :Multidimensional index iterator.
Return an iterator yielding pairs of array coordinates and values.
* ndindex() : An N-dimensional iterator object to index arrays.
 Given the shape of an array, an ndindex instance iterates over the N-dimensional index of the array. At each iteration a tuple of indices is returned, the last dimension is iterated over first.

In [2]:
import numpy as np
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆)
NOTE:
* meshgrid() : Return coordinate matrices from coordinate vectors.
Make N-D coordinate arrays for vectorized evaluations of N-D scalar/vector fields over N-D grids, given one-dimensional coordinate arrays x1, x2,…, xn.

In [3]:
import numpy as np
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆)

In [4]:

import numpy as np
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆)
Note:
* np.random.rand() : Random values in a given shape.
Create an array of the given shape and populate it with random samples from a uniform distribution over 

In [ ]:

import numpy as np
X = np.random.rand(5, 10)

# Recent versions of numpy
Y = X - X.mean(axis=1, keepdims=True)

# Older versions of numpy
Y = X - X.mean(axis=1).reshape(-1, 1)

print(Y)

#### 59. How to sort an array by the nth column? (★★☆)
Note:
* argsort() : Returns the indices that would sort an array.
Perform an indirect sort along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in sorted order.

In [5]:

import numpy as np
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[9 4 2]
 [8 9 3]
 [8 2 9]]
[[8 2 9]
 [9 4 2]
 [8 9 3]]


#### 60. How to tell if a given 2D array has null columns? (★★☆)
Note: 
* any() : The any() method returns True if any element of an iterable is True. If not, any() returns False.

In [47]:

import numpy as np
Z = np.random.randint(0,3,(3,10))
print(Z)
print((~Z.any(axis=0)).any())

[[2 0 2 1 1 1 2 0 0 1]
 [1 2 0 1 1 0 0 0 2 2]
 [0 0 1 0 1 1 1 1 0 1]]
False


#### 61. Find the nearest value from a given value in an array (★★☆)

In [50]:
import numpy as np
Z = np.random.uniform(0,1,10)
print('\n Z:',Z)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print('\n m:',m)


 Z: [0.45549062 0.3685543  0.27266264 0.22980971 0.91314574 0.97131893
 0.71932825 0.72247346 0.64907431 0.68945165]

 m: 0.4554906185139401


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆)

In [53]:
import numpy as np
A = np.arange(3).reshape(3,1)
print('\n',A)
B = np.arange(3).reshape(1,3)
print('\n',B)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print('\n',it.operands[2])


 [[0]
 [1]
 [2]]

 [[0 1 2]]

 [[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆)

In [1]:
import numpy as np
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.info = getattr(obj, 'name', "no name")

Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★)

In [45]:

import numpy as np
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)

# Another solution
np.add.at(Z, I, 1)
print(Z)

[3. 3. 1. 1. 3. 4. 4. 5. 3. 3.]
[5. 5. 1. 1. 5. 7. 7. 9. 5. 5.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★)

In [44]:

import numpy as np
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★)
Note:
* unique() : Find the unique elements of an array.
- Returns the sorted unique elements of an array. There are three optional outputs in addition to the unique elements:

    - the indices of the input array that give the unique values
    - the indices of the unique array that reconstruct the input array
    - the number of times each unique value comes up in the input array

In [56]:

import numpy as np
w,h = 16,16
I = np.random.randint(0,2,(h,w,3)).astype(np.ubyte)
#Note that we should compute 256*256 first. 
#Otherwise numpy will only promote F.dtype to 'uint16' and overfolw will occur
F = I[...,0]*(256*256) + I[...,1]*256 +I[...,2]
print(F)
n = len(np.unique(F))
print('\n',n)

[[65793   257   257 65537 65792     1     1 65792   257 65536 65536 65537
  65537     0   257 65536]
 [65793 65537 65792     1 65793   256     1     0 65793   256 65537 65792
      1 65792   256   256]
 [65537     0     1 65792 65536   256     0     1 65536   257 65537 65793
      1 65537   257 65793]
 [65536   256 65536 65792 65536     0   257     1 65793     1   257   256
    257 65793 65793 65537]
 [    0 65536 65536   256   256     0 65536 65792   257     1 65792 65536
    256     0 65537 65537]
 [  256     1     0   256 65537 65792 65536 65792   257   257 65793 65792
  65537   257 65793 65792]
 [  256 65537     0     1     0 65793 65793 65793 65793   256   257 65792
  65792 65793 65793     0]
 [65537   256 65792   257   256     1     0 65537 65793 65537   256 65536
  65537   257   256     1]
 [65793 65792   256 65537 65792 65793   256     1     0 65536 65792     1
    257 65536     0 65536]
 [65792     1 65536 65536 65793     1     1 65793     1 65536   257 65793
      1 65537    

#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★)

In [43]:

import numpy as np
A = np.random.randint(0,10,(3,4,3,4))
print('\n A :',A)
# solution by passing a tuple of axes (introduced in numpy 1.7.0)
sum = A.sum(axis=(-2,-1))
print('\n Sum :',sum)
# solution by flattening the last two dimensions into one
# (useful for functions that don't accept tuples for axis argument)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print('\n sum :',sum)


 A : [[[[7 7 7 3]
   [4 6 1 2]
   [2 9 4 7]]

  [[6 6 4 9]
   [4 2 3 7]
   [6 4 5 1]]

  [[8 2 5 7]
   [6 4 9 2]
   [9 4 0 4]]

  [[8 5 0 5]
   [5 7 9 4]
   [0 3 9 5]]]


 [[[3 4 4 9]
   [6 2 6 9]
   [9 4 1 3]]

  [[2 4 2 7]
   [2 4 2 7]
   [1 3 0 8]]

  [[0 1 5 2]
   [2 5 6 7]
   [1 9 7 5]]

  [[6 4 5 3]
   [6 7 6 0]
   [7 3 7 2]]]


 [[[9 9 3 0]
   [4 9 0 2]
   [5 3 3 8]]

  [[6 1 1 0]
   [4 5 9 7]
   [2 5 9 2]]

  [[6 7 4 7]
   [0 4 9 2]
   [6 0 9 7]]

  [[7 5 1 1]
   [0 9 8 2]
   [8 3 8 2]]]]

 Sum : [[59 57 60 60]
 [60 42 50 56]
 [55 51 61 54]]

 sum : [[59 57 60 60]
 [60 42 50 56]
 [55 51 61 54]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★)

In [58]:

import numpy as np
D = np.random.uniform(0,1,100)
print(D)
S = np.random.randint(0,10,100)
print(S)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print('\n',D_means)



[0.52981622 0.28921088 0.02018237 0.7165112  0.8294384  0.42366804
 0.74890767 0.69990823 0.09373552 0.33740286 0.48299367 0.70688804
 0.06245139 0.30787583 0.65910762 0.7939158  0.20837939 0.6047668
 0.52432657 0.18720197 0.88815577 0.37513665 0.92100063 0.99319649
 0.1115748  0.05631168 0.72058277 0.70448883 0.16869926 0.9937358
 0.00458164 0.19840333 0.85251994 0.46256204 0.49186935 0.99604005
 0.13311797 0.67804301 0.5084768  0.96001036 0.64511752 0.98063134
 0.76271796 0.46237155 0.27325683 0.77513356 0.25689562 0.88828769
 0.47815476 0.36987817 0.74796832 0.21978054 0.46338272 0.10082351
 0.86788037 0.52020922 0.98861048 0.78255547 0.44426776 0.84191521
 0.49055876 0.22869407 0.57659739 0.46932551 0.61557281 0.29498482
 0.86722236 0.25658245 0.8575559  0.99216586 0.41116395 0.4768996
 0.23066776 0.67284186 0.41479732 0.82236796 0.54334534 0.58400111
 0.61778747 0.78842755 0.59004104 0.28376422 0.27790992 0.46964954
 0.21211688 0.8605025  0.69271653 0.48528298 0.57256982 0.5483079

#### 69. How to get the diagonal of a dot product? (★★★)
Note:
* dot() : Dot product of two arrays. Specifically,

    - If both a and b are 1-D arrays, it is inner product of vectors (without complex conjugation).

    - If both a and b are 2-D arrays, it is matrix multiplication, but using matmul or a @ b is preferred.

    - If either a or b is 0-D (scalar), it is equivalent to multiply and using numpy.multiply(a, b) or a * b is preferred.

    - If a is an N-D array and b is a 1-D array, it is a sum product over the last axis of a and b.

    - If a is an N-D array and b is an M-D array (where M>=2), it is a sum product over the last axis of a and the second-to-last axis of b:

      * dot(a, b)[i,j,k,m] = sum(a[i,j,:] * b[k,:,m])
* einsum() : Evaluates the Einstein summation convention on the operands.

In [59]:

import numpy as np
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))

# Slow version  
np.diag(np.dot(A, B))

# Fast version
np.sum(A * B.T, axis=1)

# Faster version
np.einsum("ij,ji->i", A, B)#Evaluates the Einstein summation convention on the operands.

array([0.77524072, 2.55247268, 1.14579622, 1.78253573, 0.76175901])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★)

In [6]:

import numpy as np
Z = np.array([1,2,3,4,5])
y=len(Z)
print('len : ',y)
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
print(Z0)
Z0[::nz+1] = Z
print(Z0)

len :  5
[0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★)

In [33]:
import numpy as np
A = np.ones((5,5,3))
print('\n A :',A)
B = 2*np.ones((5,5))
print('\n B :',B)
print('\n A*B : ',A * B[:,:,None])


 A : [[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]

 B : [[2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]
 [2. 2. 2. 2. 2.]]

 A*B :  [[[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]

 [[2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]
  [2. 2. 2.]]]


#### 72. How to swap two rows of an array? (★★★)

In [27]:

import numpy as np
A = np.arange(25).reshape(5,5)
print(A)
A[[0,1]] = A[[1,0]]#swaping 
print(A)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]
[[ 5  6  7  8  9]
 [ 0  1  2  3  4]
 [10 11 12 13 14]
 [15 16 17 18 19]
 [20 21 22 23 24]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★)

In [60]:

import numpy as np
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 1,  8) ( 1, 87) ( 4, 10) ( 4, 78) ( 5, 35) ( 5, 84) ( 8, 87) ( 9, 21)
 ( 9, 50) ( 9, 84) ( 9, 87) (10, 19) (10, 78) (10, 80) (19, 80) (21, 50)
 (35, 84) (39, 47) (39, 90) (41, 42) (41, 56) (42, 56) (47, 90) (53, 65)
 (53, 96) (65, 96) (77, 82) (77, 85) (82, 85) (84, 87)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★)

In [12]:

import numpy as np
C = np.bincount([1,1,2,3,4,4,6])
print(C)
A = np.repeat(np.arange(len(C)), C)#repeat():Repeat elements of an array.
print(A)

[0 2 1 1 2 0 1]
[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★)
Note : 
* cumsum () : Return the cumulative sum of the elements along a given axis.
* moving_average() : Return the moving averages of the data, with a window size of sample_size. sample_size must be an integer greater than 0.

In [13]:

import numpy as np
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    print(ret)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))

[  0.   1.   3.   6.  10.  15.  21.  28.  36.  45.  55.  66.  78.  91.
 105. 120. 136. 153. 171. 190.]
[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★)

In [24]:

import numpy as np
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)
Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★)

In [62]:

import numpy as np
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)#Compute the truth value of NOT x element-wise.

Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.60225198,  0.64961688,  0.46333176,  0.20737365,  0.93645702,
        0.11526988, -0.0111101 , -0.59038585, -0.46609364,  0.83132905,
        0.07618739, -0.15748376, -0.7941901 , -0.41088424,  0.53012808,
        0.45237825, -0.56875489, -0.70798984,  0.91173085,  0.31425619,
        0.71043157,  0.00310414,  0.03931771,  0.59149566,  0.89463396,
        0.97796643, -0.44502057, -0.54792076,  0.84189124,  0.24538151,
        0.20364012,  0.63276793,  0.66717085,  0.68254288, -0.73322708,
        0.8909654 , -0.19131321, -0.71634476,  0.77791498, -0.79867784,
        0.06068101,  0.36410264,  0.64567589,  0.15278908, -0.90864962,
        0.50891161, -0.87026295,  0.31847417, -0.13522039, -0.87431816,
       -0.11967945, -0.34945562,  0.14315957, -0.11148985, -0.04925829,
       -0.15463071, -0.04844387,  0.46323354, -0.29776598, -0.8113449 ,
        0.15731807, -0.38498401, -0.54712836,  0.43471847,  0.11354456,
        0.77574141, -0.5525115 , -0.75842073, -0.23202294,  0.83

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [17]:
import numpy as np
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))

P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[ 4.04416438  7.73557399  1.45510914  8.78912469  8.44607345  9.6441782
  7.40770811 11.86532384  0.07943601  5.6197767 ]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [22]:

import numpy as np
def distance(P0, P1, p):
# based on distance function from previous question
    P0 = np.random.uniform(-10, 10, (10,2))
    P1 = np.random.uniform(-10,10,(10,2))
    p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[None]


#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★)

In [ ]:

import numpy as np
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★)

In [ ]:

import numpy as np
Z = np.arange(1,15,dtype=np.uint32)
R = stride_tricks.as_strided(Z,(11,4),(4,4))
print(R)

#### 82. Compute a matrix rank (★★★)
Note:
* np.linalg.svd() : ingular Value Decomposition.
When a is a 2D array, it is factorized as u @ np.diag(s) @ vh = (u * s) @ vh, where u and vh are 2D unitary arrays and s is a 1D array of a’s singular values. When a is higher-dimensional, SVD is applied in stacked mode 

In [17]:

import numpy as np
Z = np.random.uniform(0,1,(10,10))
print(Z)
U, S, V = np.linalg.svd(Z) # Singular Value Decomposition
print('\n',U)
rank = np.sum(S > 1e-10)
print(rank)

[[0.09211166 0.71962109 0.97155569 0.26901622 0.28512393 0.77385543
  0.60243733 0.49187694 0.79683244 0.87193847]
 [0.62621826 0.56317887 0.9112645  0.11752374 0.2139248  0.02518053
  0.30725293 0.45572541 0.27181733 0.30860647]
 [0.40781763 0.82346187 0.43924434 0.49899237 0.31695624 0.39548514
  0.03009022 0.88508681 0.60431004 0.13380307]
 [0.36400416 0.72989088 0.21548158 0.58299798 0.59310977 0.65905784
  0.24545231 0.2266383  0.16612378 0.8173916 ]
 [0.99378287 0.70083344 0.34607392 0.73711209 0.85971523 0.35292034
  0.55225041 0.35319502 0.67428711 0.96693877]
 [0.79057892 0.45652904 0.93891366 0.90675552 0.37064353 0.54092845
  0.04270314 0.52032949 0.17906631 0.90314461]
 [0.42141935 0.42520275 0.98380097 0.9699799  0.89916806 0.98369777
  0.11281566 0.76236673 0.7576399  0.09546568]
 [0.84674169 0.33145426 0.07843608 0.04787682 0.97759232 0.84039561
  0.86568234 0.20681576 0.40057449 0.318894  ]
 [0.60447943 0.62878177 0.27640904 0.74047212 0.09155989 0.97437149
  0.29133853

#### 83. How to find the most frequent value in an array?

In [21]:
import numpy as np
Z = np.random.randint(0,10,50)
print(Z)
print(np.bincount(Z).argmax())

[8 3 6 2 7 3 1 8 1 6 7 1 4 6 6 2 9 8 2 2 9 7 4 3 7 0 7 5 9 5 9 9 0 0 3 1 2
 7 6 5 3 4 0 9 0 9 2 5 6 2]
2


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★)

In [22]:

import numpy as np
Z = np.random.randint(0,5,(10,10))
n = 3
i = 1 + (Z.shape[0]-3)
j = 1 + (Z.shape[1]-3)
C = stride_tricks.as_strided(Z, shape=(i, j, n, n), strides=Z.strides + Z.strides)
print(C)

NameError: name 'stride_tricks' is not defined

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★)

In [23]:

# Note: only works for 2d array and value setting using indices
import numpy as np
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 5  4  9  0  4]
 [ 4  1  8  5 16]
 [ 9  8  4 42  2]
 [ 0  5 42  7  5]
 [ 4 16  2  5  3]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★)
Note:
* tensordot() : Compute tensor dot product along specified axes for arrays >= 1-D.
Given two tensors (arrays of dimension greater than or equal to one), a and b, and an array_like object containing two array_like objects, (a_axes, b_axes), sum the products of a‘s and b‘s elements (components) over the axes specified by a_axes and b_axes. The third argument can be a single non-negative integer_like scalar, N; if it is such, then the last N dimensions of a and the first N dimensions of b are summed over.

In [30]:

import numpy as np
p, n = 2, 5
M = np.ones((p,n,n))
print('\n M :',M)
V = np.ones((p,n,1))
print('\n V:',V)
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print('\n S: ',S)


# It works, because:
# M is (p,n,n)
# V is (p,n,1)
# Thus, summing over the paired axes 0 and 0 (of M and V independently),
# and 2 and 1, to remain with a (n,1) vector.


 M : [[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]

 V: [[[1.]
  [1.]
  [1.]
  [1.]
  [1.]]

 [[1.]
  [1.]
  [1.]
  [1.]
  [1.]]]

 S:  [[10.]
 [10.]
 [10.]
 [10.]
 [10.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★)
* reduceat(): Performs a (local) reduce with specified slices over a single axis.
For i in range(len(indices)), reduceat computes ufunc.reduce(a[indices[i]:indices[i+1]]), which becomes the i-th generalized “row” parallel to axis in the final result (i.e., in a 2-D array, for example, if axis = 0, it becomes the i-th row, but if axis = 1, it becomes the i-th column). There are three exceptions to this:

   - when i = len(indices) - 1 (so for the last index), indices[i+1] = a.shape[axis].
   - if indices[i] >= indices[i + 1], the i-th generalized “row” is simply a[indices[i]].
   - if indices[i] >= len(a) or indices[i] < 0, an error is raised.
* The shape of the output depends on the size of indices, and may be larger than a (this happens if len(indices) > a.shape[axis]).

In [45]:

import numpy as np
Z = np.ones((15,16))
k = 4
z=np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0)
print(z)
S = np.add.reduceat(np.add.reduceat(Z, np.arange(0, Z.shape[0], k), axis=0),
                                       np.arange(0, Z.shape[1], k), axis=1)
print(S)

[[4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4. 4.]
 [3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3. 3.]]
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [12. 12. 12. 12.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [49]:

import numpy as np
def iterate(Z):
    # Count neighbours
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    #print(N)

    # Apply rules
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print('\n',Z)


 [[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★)
Note:
* np.random.shuffle() :Modify a sequence in-place by shuffling its contents.
This function only shuffles the array along the first axis of a multi-dimensional array. The order of sub-arrays is changed but their contents remains the same.
*  argpartition(): Perform an indirect partition along the given axis using the algorithm specified by the kind keyword. It returns an array of indices of the same shape as a that index data along the given axis in partitioned order.

In [50]:
import numpy as np
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5

# Slow
print (Z[np.argsort(Z)[-n:]])

# Fast
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9999 9996 9998 9997]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★)
Note:
* indices() : Return an array representing the indices of a grid.
Compute an array where the subarrays contain index values 0,1,… varying only along the corresponding axis.
* Enumerate() : method adds a counter to an iterable and returns it in a form of enumerate object. This enumerate object can then be used directly in for loops or be converted into a list of tuples using list() method.

In [54]:

import numpy as np
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    #print('\n IX :',ix)
    ix = ix.reshape(len(arrays), -1).T
    #print('\n IX :',ix)
    for n, arr in enumerate(arrays):#
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print ('\n',cartesian(([1, 2, 3], [4, 5], [6, 7])))


 [[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★)

In [56]:
import numpy as np
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
print(Z)
R = np.core.records.fromarrays(Z.T, 
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')#create a record array from a (flat) list of arrays
print(R)

[['Hello' '2.5' '3']
 ['World' '3.6' '2']]
[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★)

In [70]:

import numpy as np
x = np.random.rand(5e7)
print(x)

%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

TypeError: 'float' object cannot be interpreted as an integer

#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★)

In [67]:

import numpy as np
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))

C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[0 1 2 3 5 6]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [8]:

import numpy as np
Z = np.random.randint(0,5,(10,3))
print(Z)
# solution for arrays of all dtypes (including string arrays and record arrays)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
# soluiton for numerical arrays only, will work for any number of columns in Z
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[2 0 1]
 [0 2 3]
 [4 0 0]
 [3 2 3]
 [3 2 3]
 [3 0 4]
 [0 1 4]
 [0 4 2]
 [0 1 3]
 [0 3 3]]
[[2 0 1]
 [0 2 3]
 [4 0 0]
 [3 2 3]
 [3 2 3]
 [3 0 4]
 [0 1 4]
 [0 4 2]
 [0 1 3]
 [0 3 3]]
[[2 0 1]
 [0 2 3]
 [4 0 0]
 [3 2 3]
 [3 2 3]
 [3 0 4]
 [0 1 4]
 [0 4 2]
 [0 1 3]
 [0 3 3]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★)

In [9]:

import numpy as np
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128])
B = ((I.reshape(-1,1) & (2**np.arange(8))) != 0).astype(int)
print(B[:,::-1])



I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]
[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### *****96. Given a two dimensional array, how to extract unique rows? (★★★)

In [66]:

import numpy as np
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))#Return a contiguous array (ndim >= 1) in memory (C order).
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

# NumPy >= 1.13
uZ = np.unique(Z, axis=0)
print(uZ)

IndentationError: unexpected indent (<ipython-input-66-21f4e15c4ace>, line 5)

#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★)

In [11]:


import numpy as np
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)

np.einsum('i->', A)       # np.sum(A)
np.einsum('i,i->i', A, B) # A * B
np.einsum('i,i', A, B)    # np.inner(A, B)
np.einsum('i,j->ij', A, B)    # np.outer(A, B)

array([[0.39814403, 0.16039272, 0.51131389, 0.32463486, 0.34760873,
        0.34827928, 0.37318741, 0.49192937, 0.3143322 , 0.34563946],
       [0.24315351, 0.09795463, 0.31226832, 0.19826018, 0.21229072,
        0.21270023, 0.22791206, 0.30042986, 0.19196816, 0.21108805],
       [0.31826093, 0.12821173, 0.40872453, 0.25950054, 0.27786496,
        0.27840097, 0.29831156, 0.39322929, 0.25126499, 0.2762908 ],
       [0.39092617, 0.15748499, 0.50204439, 0.31874963, 0.34130701,
        0.3419654 , 0.36642197, 0.48301129, 0.30863374, 0.33937344],
       [0.02014972, 0.00811734, 0.02587715, 0.01642949, 0.01759218,
        0.01762611, 0.01888669, 0.02489612, 0.01590808, 0.01749251],
       [0.56036179, 0.2257423 , 0.71964099, 0.45690242, 0.48923664,
        0.49018039, 0.52523696, 0.69235855, 0.44240209, 0.48646503],
       [0.5315735 , 0.21414491, 0.68266982, 0.4334293 , 0.46410237,
        0.46499764, 0.4982532 , 0.65678899, 0.41967392, 0.46147315],
       [0.14208488, 0.05723903, 0.1824715

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)?

In [13]:

import numpy as np
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)

dr = (np.diff(x)**2 + np.diff(y)**2)**.5 # segment lengths
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)                # integrate path
r_int = np.linspace(0, r.max(), 200) # regular spaced path
x_int = np.interp(r_int, r, x)       # integrate path
y_int = np.interp(r_int, r, y)

#### ******99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★)

In [63]:

import numpy as np
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
print(X)
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print('\n',X[M])

[[1.  0.  3.  8. ]
 [2.  0.  1.  1. ]
 [1.5 2.5 1.  0. ]]

 [[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★)

In [15]:

import numpy as np
X = np.random.randn(100) # random 1D array
N = 1000 # number of bootstrap samples
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.02155682  0.37780181]
